//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fedyaev_Petrov_Namordik.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VM_ProductList
    {
        public string NameProduct { get; set; }
        public string TypeProduct { get; set; }
        public string Articul { get; set; }
        public decimal Cost { get; set; }
        public string Material { get; set; }
        public Nullable<int> QtyLastSaleProduct { get; set; }
        public string Image { get; set; }
    }
}
