//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fedyaev_Petrov_Namordik.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VM_ProductList
    {
        public string Название_продукта { get; set; }
        public string Тип_продукта { get; set; }
        public string Артикул { get; set; }
        public decimal Стоимость { get; set; }
        public string Материалы { get; set; }
    }
}
